# Define the name of the workflow.
name: Go

# Define when the workflow should run.
on:
  # Triggered when changes are pushed to files with a .go extension.
  push:
    paths:
      - "**.go"

# Define the jobs to be executed.
jobs:
  # Define the build job.
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # Check out code from the repository.
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      
      # Get the current version of Go from the project and set it as an environment variable.
      - name: Get the current version of Go from project.
        run: type go.mod | select -first 3 | select -last 1 | %{ 'GO_VERSION_FROM_PROJECT={1}' -f ($_ -split ' ') } >>$env:GITHUB_ENV
      
      # Set up the specified Go version.
      - name: Set up Go version "${{ env.GO_VERSION_FROM_PROJECT }}"
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION_FROM_PROJECT }}"
        id: go
      
      # Get Go dependencies.
      - name: Get dependencies
        run: go get .
      
      # Build the Go application.
      - name: Build Test
        run: go build .
